server:
  port: 8080
  servlet:
    context-path: /jsonar
spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  devtools:
    restart:
      enabled: true

